spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: local
  application:
    name: study
  mvc:
    throw-exception-if-no-handler-found: true
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
server:
  port: 8080
  undertow:
    io-threads: 4
    worker-threads: 50
    buffer-size: 512
    direct-buffers: true
    accesslog:
      enabled: true
      dir: ${logging.path}/undertow/${spring.application.name}
      pattern: combined
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
logging:
  home: ${logging.path}/${spring.application.name}
  file: ${logging.home}/${spring.application.name}.log
  path: /logs
  level:
    root: info